name: CI Pipeline
on:
  push:
    branches:
       - Main
jobs:
   write-hello:
     runs-on: ubuntu-latest
    
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
       
       - name: print Hello
         run: echo "Hello World this from Github"

       - name: Show Files
         run: ls
